version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'bingo'
      MYSQL_USER: 'bingo'
      MYSQL_PASSWORD: 'bingotesting'
      MYSQL_ROOT_PASSWORD: 'rootbingotesting'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
  backend:
    build: .
    ports:
      - "3000:3000"
    restart: always
  # frontend:
  #   image: frontend
    
volumes:
  mysql_data:
